name: procap-atlas
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.0
  - uv
  - wget
  - parallel
  - samtools
  - htslib
  - ucsc-bigwigmerge
  - ucsc-bedgraphtobigwig
  - ucsc-bedtobigbed
