#!/usr/bin/env python3
"""
Compare BPNet and Cherimoya benchmark metrics across ENCODE PRO-cap atlas
experiments.

For each shared metric, produces one figure with a scatterplot (BPNet vs.
Cherimoya, one point per experiment, colored by read depth, with a y=x
reference line and a Wilcoxon signed-rank test) and a histogram of
per-experiment deltas (Cherimoya minus BPNet).

Reads the consolidated per-model TSVs (generated by
src/cherimoya/benchmark/consolidate_metrics.py and its BPNet equivalent) and
inner-joins on experiment, so only experiments benchmarked for both models are
included.

Usage:
    python src/analysis/compare_bpnet_cherimoya.py
    python src/analysis/compare_bpnet_cherimoya.py --metrics profile_jsd
    python src/analysis/compare_bpnet_cherimoya.py --min-reads 10000000
"""

import argparse
import sys
from pathlib import Path

import pandas as pd

from _metric_comparison_plots import plot_metric_comparison

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_BPNET_TSV = (
    REPO_ROOT / "performance_metrics" / "bpnet" / "procap-atlas_performance_metrics.tsv"
)
DEFAULT_CHERIMOYA_TSV = (
    REPO_ROOT / "performance_metrics" / "cherimoya" / "procap-atlas_performance_metrics.tsv"
)
DEFAULT_OUT_DIR = REPO_ROOT / "plots" / "bpnet_vs_cherimoya"

# lower_is_better controls delta sign convention (Cherimoya - BPNet) and which
# side of zero/the diagonal counts as a Cherimoya improvement.
METRIC_INFO = {
    "profile_jsd": {"label": "profile JSD", "lower_is_better": True},
    "log_counts_pearson": {"label": "log-counts Pearson", "lower_is_better": False},
}


def parse_args():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--bpnet-tsv",
        type=Path,
        default=DEFAULT_BPNET_TSV,
        help=f"BPNet consolidated metrics TSV (default: {DEFAULT_BPNET_TSV.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--cherimoya-tsv",
        type=Path,
        default=DEFAULT_CHERIMOYA_TSV,
        help=f"Cherimoya consolidated metrics TSV (default: {DEFAULT_CHERIMOYA_TSV.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help=f"directory for figure output (default: {DEFAULT_OUT_DIR.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--metrics",
        nargs="+",
        choices=sorted(METRIC_INFO),
        default=sorted(METRIC_INFO),
        help="metrics to compare (default: all)",
    )
    parser.add_argument(
        "--min-reads",
        type=float,
        default=0,
        help="skip experiments with fewer than N total reads (default: 0)",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    for path, model_label in [(args.bpnet_tsv, "BPNet"), (args.cherimoya_tsv, "Cherimoya")]:
        if not path.exists():
            print(f"ERROR: {model_label} metrics TSV not found: {path}", file=sys.stderr)
            sys.exit(1)

    bpnet = pd.read_csv(args.bpnet_tsv, sep="\t")
    cherimoya = pd.read_csv(args.cherimoya_tsv, sep="\t")

    metrics = [m for m in args.metrics if m in bpnet.columns and m in cherimoya.columns]
    missing = sorted(set(args.metrics) - set(metrics))
    if missing:
        print(
            f"WARNING: metrics not present in both TSVs, skipping: {missing}",
            file=sys.stderr,
        )
    if not metrics:
        print("ERROR: none of the requested metrics are present in both TSVs", file=sys.stderr)
        sys.exit(1)

    # Inner join: keeps only experiments benchmarked for both models
    cols = ["experiment", "biosample", "total_reads", *metrics]
    df = bpnet[cols].merge(
        cherimoya[["experiment", *metrics]],
        on="experiment",
        suffixes=("_bpnet", "_cherimoya"),
    )
    df = df[df["total_reads"] >= args.min_reads]

    if len(df) < 2:
        print(
            f"ERROR: fewer than 2 shared experiments after filtering ({len(df)})",
            file=sys.stderr,
        )
        sys.exit(1)

    print(
        f"{len(df)} experiments shared between BPNet and Cherimoya benchmarks",
        file=sys.stderr,
    )

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for metric in metrics:
        info = METRIC_INFO[metric]
        out_path = args.out_dir / f"bpnet_vs_cherimoya_{metric}.pdf"
        median_delta, mean_delta = plot_metric_comparison(
            df,
            col_a=f"{metric}_bpnet",
            col_b=f"{metric}_cherimoya",
            label_a="BPNet",
            label_b="Cherimoya",
            metric_label=info["label"],
            lower_is_better=info["lower_is_better"],
            read_depth_col="total_reads",
            out_path=out_path,
        )
        print(
            f"{info['label']}: median delta={median_delta:.4f}, mean delta={mean_delta:.4f}",
            file=sys.stderr,
        )
        print(f"Saved {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
